'use client'
import { useState, useEffect } from 'react'

/*
 * PredictionTable — Shows 24-48 hour grid usage forecasts
 * 
 * HOW IT WORKS:
 * 1. On mount, fetches /predictions.json from the public folder
 * 2. This file is generated by the Prophet ML model (currently mock data)
 * 3. Each row shows: timestamp, predicted MW, capacity %, and risk level
 * 4. Risk levels are color-coded: safe (green), warning (amber), critical (red)
 * 5. User can toggle between 24-hour and 48-hour views
 * 
 * WHEN PROPHET MODEL IS READY:
 * Just run predict.py → it outputs predictions.json → copy to /public/
 * This component automatically picks it up. Zero code changes needed.
 */
export default function PredictionTable() {
  const [predictions, setPredictions] = useState([])
  const [show48, setShow48] = useState(false)  // toggle between 24h and 48h view

  useEffect(() => {
    fetch('/predictions.json')
      .then(r => r.json())
      .then(d => setPredictions(d.predictions ?? []))
      .catch(() => console.error('Failed to load predictions'))
  }, [])

  // Slice based on toggle — 24 or all 48 entries
  const displayData = show48 ? predictions : predictions.slice(0, 24)

  // Risk level badge styles
  const riskStyles = {
    safe:     { color: '#00c853', bg: 'rgba(0, 200, 83, 0.08)',  border: 'rgba(0, 200, 83, 0.2)' },
    warning:  { color: '#ff9500', bg: 'rgba(255, 149, 0, 0.08)', border: 'rgba(255, 149, 0, 0.2)' },
    critical: { color: '#ff3b30', bg: 'rgba(255, 59, 48, 0.08)', border: 'rgba(255, 59, 48, 0.2)' },
  }

  // Find the highest risk entry to highlight it
  const maxRiskIdx = predictions.reduce((maxI, p, i, arr) =>
    p.predicted_mw > (arr[maxI]?.predicted_mw ?? 0) ? i : maxI, 0)

  return (
    <div style={{
      background: '#0a0a0a',
      border: '1px solid rgba(255,255,255,0.08)',
      borderRadius: '12px',
      padding: '32px',
      fontFamily: "'Inter', sans-serif",
    }}>
      {/* Header with toggle */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '24px',
      }}>
        <div>
          <h2 style={{ fontSize: '18px', fontWeight: '600', color: '#ededed', margin: 0 }}>
            Grid Forecast
          </h2>
          <p style={{ fontSize: '13px', color: '#555', margin: '4px 0 0' }}>
            Prophet ML predictions • Hourly breakdown
          </p>
        </div>
        {/* 24h / 48h toggle button */}
        <button
          onClick={() => setShow48(!show48)}
          style={{
            background: '#1a1a1a',
            border: '1px solid rgba(255,255,255,0.1)',
            borderRadius: '6px',
            padding: '6px 14px',
            color: '#888',
            fontSize: '13px',
            cursor: 'pointer',
            fontFamily: "'Inter', sans-serif",
            transition: 'border-color 0.2s',
          }}
        >
          {show48 ? 'Show 24h' : 'Show 48h'}
        </button>
      </div>

      {/* Table */}
      <div style={{ overflowY: 'auto', maxHeight: '400px' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '14px' }}>
          <thead>
            <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
              {['Time', 'Predicted', 'Capacity', 'Risk'].map(h => (
                <th key={h} style={{
                  padding: '8px 0 12px',
                  fontSize: '12px',
                  fontWeight: '500',
                  color: '#555',
                  textAlign: h === 'Time' ? 'left' : 'right',
                  textTransform: 'uppercase',
                  letterSpacing: '0.5px',
                }}>
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {displayData.map((p, i) => {
              const risk = riskStyles[p.risk_level] || riskStyles.safe
              const isMax = i === maxRiskIdx
              return (
                <tr
                  key={i}
                  style={{
                    borderBottom: '1px solid rgba(255,255,255,0.04)',
                    borderLeft: isMax ? '2px solid #ff3b30' : '2px solid transparent',
                    transition: 'background 0.15s',
                  }}
                  onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,255,255,0.03)'}
                  onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                >
                  {/* Time */}
                  <td style={{ padding: '10px 8px 10px 12px', color: '#ededed' }}>
                    {new Date(p.timestamp).toLocaleString('en-CA', {
                      weekday: 'short', hour: 'numeric', hour12: true
                    })}
                  </td>
                  {/* Predicted MW */}
                  <td style={{
                    padding: '10px 0',
                    textAlign: 'right',
                    color: '#ededed',
                    fontFamily: "'SF Mono', 'Fira Code', monospace",
                    fontWeight: '500',
                  }}>
                    {p.predicted_mw.toLocaleString()} MW
                  </td>
                  {/* Capacity % */}
                  <td style={{
                    padding: '10px 0',
                    textAlign: 'right',
                    color: '#888',
                    fontFamily: "'SF Mono', 'Fira Code', monospace",
                  }}>
                    {p.capacity_pct}%
                  </td>
                  {/* Risk badge */}
                  <td style={{ padding: '10px 0', textAlign: 'right' }}>
                    <span style={{
                      display: 'inline-block',
                      padding: '3px 10px',
                      borderRadius: '4px',
                      fontSize: '11px',
                      fontWeight: '600',
                      textTransform: 'uppercase',
                      letterSpacing: '0.5px',
                      color: risk.color,
                      background: risk.bg,
                      border: `1px solid ${risk.border}`,
                    }}>
                      {p.risk_level}
                    </span>
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      {predictions.length === 0 && (
        <div style={{ textAlign: 'center', padding: '40px 0', color: '#555' }}>
          No prediction data available. Run predict.py to generate forecasts.
        </div>
      )}
    </div>
  )
}